jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: google/wireit@setup-github-actions-caching/v2

      - uses: changesets/action@v1
        with:
          publish: npm run publish:changeset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    timeout-minutes: 10

on:
  push:
    branches:
      - main
